version: '3.2'
services:
  easywall:
    image: easywall
    build:
      context: .
    container_name: easywall
    restart: unless-stopped
    ports: 
      - "12227:12227"
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "/srv/easywall/config:/config"
      #- "/srv/easywall/easywall.log:/var/log/easywall.log" # Optional, and file needs to exist in host.
      #- "/certs/ssl.crt:/ssl/easywall.crt" # Optional, and needed to enable HTTPS by default
      #- "/certs/ssl.key:/ssl/easywall.key" # Optional, and needed to enable HTTPS by default
