version: '3.2'
services:
  easywall:
    image: easywall
    build:
      context: .
    container_name: easywall
    restart: unless-stopped
    ports: 
      - "12227:12227"
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "/srv/easywall/config:/config"
